-- Development-only authentication seed data.
--
-- Replace password_hash values with hashes generated by the application before
-- using these users. These rows are intentionally deterministic so two local
-- databases can be created with the same IDs.

PRAGMA foreign_keys = ON;
PRAGMA busy_timeout = 5000;

BEGIN;

INSERT OR IGNORE INTO roles (id, name, description) VALUES
    ('11111111-1111-4111-8111-111111111111', 'admin',
        'Full access to the hackathon middleware'),
    ('11111111-1111-4111-8111-222222222222', 'developer',
        'Can invoke agents and inspect orchestration work'),
    ('11111111-1111-4111-8111-333333333333', 'viewer',
        'Read-only access to agents, runs, and results');

INSERT OR IGNORE INTO users
    (id, username, email, password_hash, display_name)
VALUES
    ('22222222-2222-4222-8222-111111111111', 'alice',
        'alice@example.test',
        'scrypt$16384$8$1$YWxpY2Utc2VlZC1zYWx0LTIwMjY$zErW6fnGadc2MqhLi8y950qaEOB2lDFT30GnHmLXV4bSNiuywZIhqLcYw0qGzTK0Wrw84SqXYljIIDfEUbmoxA',
        'Alice'),
    ('22222222-2222-4222-8222-222222222222', 'bob',
        'bob@example.test',
        'scrypt$16384$8$1$Ym9iLXNlZWQtc2FsdC0yMDI2$-PJ1g2JSj_zJmj2Bx77R79x402371sLioe49yNUHUOfP6xrjbmSOHwSi1aYMVcHsT1rnlnYvD1Ngoojefj8SCQ',
        'Bob');

-- Keep the deterministic development credentials usable when the seed is
-- re-applied to an existing local database.
UPDATE users
SET password_hash = 'scrypt$16384$8$1$YWxpY2Utc2VlZC1zYWx0LTIwMjY$zErW6fnGadc2MqhLi8y950qaEOB2lDFT30GnHmLXV4bSNiuywZIhqLcYw0qGzTK0Wrw84SqXYljIIDfEUbmoxA',
    display_name = 'Alice',
    is_active = 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '22222222-2222-4222-8222-111111111111';

UPDATE users
SET password_hash = 'scrypt$16384$8$1$Ym9iLXNlZWQtc2FsdC0yMDI2$-PJ1g2JSj_zJmj2Bx77R79x402371sLioe49yNUHUOfP6xrjbmSOHwSi1aYMVcHsT1rnlnYvD1Ngoojefj8SCQ',
    display_name = 'Bob',
    is_active = 1,
    updated_at = strftime('%Y-%m-%dT%H:%M:%fZ', 'now')
WHERE id = '22222222-2222-4222-8222-222222222222';

-- Bob is a viewer in the demo so the authorization boundary is visible.
DELETE FROM user_roles
WHERE user_id = '22222222-2222-4222-8222-222222222222'
  AND role_id = '11111111-1111-4111-8111-111111111111';

INSERT OR IGNORE INTO user_roles (user_id, role_id) VALUES
    ('22222222-2222-4222-8222-111111111111',
        '11111111-1111-4111-8111-222222222222'),
    ('22222222-2222-4222-8222-222222222222',
        '11111111-1111-4111-8111-222222222222');

DELETE FROM user_roles
WHERE user_id = '22222222-2222-4222-8222-222222222222'
  AND role_id = '11111111-1111-4111-8111-333333333333';

-- Admin wildcard permissions are explicit per resource family.
INSERT OR IGNORE INTO permissions
    (id, role_id, resource_type, resource_key, action, allowed)
VALUES
    ('55555555-5555-4555-8555-111111111111',
        '11111111-1111-4111-8111-111111111111', 'agent', '*', '*', 1),
    ('55555555-5555-4555-8555-222222222222',
        '11111111-1111-4111-8111-111111111111', 'run', '*', '*', 1),
    ('55555555-5555-4555-8555-333333333333',
        '11111111-1111-4111-8111-111111111111', 'orchestration', '*', '*', 1),
    ('55555555-5555-4555-8555-444444444444',
        '11111111-1111-4111-8111-111111111111', 'system', '*', '*', 1),
    ('55555555-5555-4555-8555-161616161616',
        '11111111-1111-4111-8111-111111111111', 'data_asset', '*', '*', 1),
    ('55555555-5555-4555-8555-555555555555',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'invoke', 1),
    ('55555555-5555-4555-8555-666666666666',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'view', 1),
    ('55555555-5555-4555-8555-777777777777',
        '11111111-1111-4111-8111-222222222222', 'run', '*', 'view', 1),
    ('55555555-5555-4555-8555-888888888888',
        '11111111-1111-4111-8111-222222222222', 'orchestration', '*', 'create', 1),
    ('55555555-5555-4555-8555-151515151515',
        '11111111-1111-4111-8111-222222222222', 'orchestration', '*', 'view', 1),
    ('55555555-5555-4555-8555-171717171717',
        '11111111-1111-4111-8111-222222222222', 'data_asset', 'order-schema', 'read', 1),
    ('55555555-5555-4555-8555-181818181818',
        '11111111-1111-4111-8111-222222222222', 'data_asset', 'backend-api-contract', 'read', 1),
    ('55555555-5555-4555-8555-191919191919',
        '11111111-1111-4111-8111-222222222222', 'data_asset', 'frontend-design-system', 'read', 1),
    ('55555555-5555-4555-8555-202020202020',
        '11111111-1111-4111-8111-222222222222', 'data_asset', 'shared-project-status', 'read', 1),
    ('55555555-5555-4555-8555-cccccccccccc',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'create', 1),
    ('55555555-5555-4555-8555-dddddddddddd',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'update', 1),
    ('55555555-5555-4555-8555-eeeeeeeeeeee',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'delete', 1),
    ('55555555-5555-4555-8555-ffffffffffff',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'start', 1),
    ('55555555-5555-4555-8555-121212121212',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'stop', 1),
    ('55555555-5555-4555-8555-131313131313',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'delegate', 1),
    ('55555555-5555-4555-8555-141414141414',
        '11111111-1111-4111-8111-222222222222', 'agent', '*', 'approve', 1),
    ('55555555-5555-4555-8555-999999999999',
        '11111111-1111-4111-8111-333333333333', 'agent', '*', 'view', 1),
    ('55555555-5555-4555-8555-aaaaaaaaaaaa',
        '11111111-1111-4111-8111-333333333333', 'run', '*', 'view', 1),
    ('55555555-5555-4555-8555-bbbbbbbbbbbb',
        '11111111-1111-4111-8111-333333333333', 'orchestration', '*', 'view', 1);

COMMIT;
